export const TIMEFRAME_CONFIG = [
    { id: '1', label: '1m', title: '1 phút', category: 'PHÚT' },
    { id: '3', label: '3m', title: '3 phút', category: 'PHÚT' },
    { id: '5', label: '5m', title: '5 phút', category: 'PHÚT' },
    { id: '10', label: '10m', title: '10 phút', category: 'PHÚT' },
    { id: '15', label: '15m', title: '15 phút', category: 'PHÚT' },
    { id: '30', label: '30m', title: '30 phút', category: 'PHÚT' },
    { id: '60', label: '1h', title: '1 giờ', category: 'GIỜ' },
    { id: '120', label: '2h', title: '2 giờ', category: 'GIỜ' },
    { id: '240', label: '4h', title: '4 giờ', category: 'GIỜ' },
    { id: '1440', label: 'D', title: '1 ngày', category: 'NGÀY' },
    { id: '10080', label: 'W', title: '1 tuần', category: 'NGÀY' },
    { id: '43200', label: 'M', title: '1 tháng', category: 'NGÀY' },
    { id: '525600', label: 'Y', title: '1 năm', category: 'NGÀY' },
];
